---
# Based on: https://docs.coolercontrol.org/installation/debian.html

- name: Check if CoolerControl is already installed
  ansible.builtin.command: dpkg-query -W {{ coolercontrol_package_name }}
  register: coolercontrol_installed
  failed_when: false
  changed_when: false

- name: Ensure curl is installed (required for repository setup script)
  ansible.builtin.apt:
    name: curl
    state: present
  become: true
  when: coolercontrol_installed.rc != 0

- name: Download CoolerControl repository setup script
  ansible.builtin.get_url:
    url: "{{ coolercontrol_setup_script_url }}"
    dest: "/tmp/coolercontrol-setup.sh"
    mode: '0700'
  become: true
  when: coolercontrol_installed.rc != 0

- name: Run CoolerControl repository setup script
  ansible.builtin.command: /tmp/coolercontrol-setup.sh
  become: true
  when: coolercontrol_installed.rc != 0

- name: Remove CoolerControl repository setup script
  ansible.builtin.file:
    path: "/tmp/coolercontrol-setup.sh"
    state: absent
  when: coolercontrol_installed.rc != 0

- name: Install CoolerControl
  ansible.builtin.apt:
    name: "{{ coolercontrol_package_name }}"
    state: present
    update_cache: true
  become: true
  when: coolercontrol_installed.rc != 0

- name: Enable and start CoolerControl daemon
  ansible.builtin.systemd:
    name: "{{ coolercontrol_service_name }}"
    enabled: true
    state: started
  become: true
